const GOTV = [
  {
    id: 17,
    cableplan_id: "17",
    cable: "GOTV",
    package: "GOtv Smallie-monthly 800",
    plan_amount: "796",
  },
  {
    id: 16,
    cableplan_id: "16",
    cable: "GOTV",
    package: "GOtv Jinja",
    plan_amount: "1640",
  },
  {
    id: 35,
    cableplan_id: "35",
    cable: "GOTV",
    package: "GOtv Smallie - Quarterly",
    plan_amount: "2100",
  },
  {
    id: 47,
    cableplan_id: "47",
    cable: "GOTV",
    package: "Gotv-jolli",
    plan_amount: "2460",
  },
  {
    id: 2,
    cableplan_id: "2",
    cable: "GOTV",
    package: "GOtv Max",
    plan_amount: "3600",
  },
  {
    id: 36,
    cableplan_id: "36",
    cable: "GOTV",
    package: "GOtv Smallie - Yearly",
    plan_amount: "6200",
  },
];
const DSTV = [
  {
    id: 33,
    cableplan_id: "33",
    cable: "DSTV",
    package: "DStv Padi 1850.",
    plan_amount: "1841",
  },
  {
    id: 6,
    cableplan_id: "6",
    cable: "DSTV",
    package: "DStv Yanga",
    plan_amount: "2565",
  },
  {
    id: 22,
    cableplan_id: "22",
    cable: "DSTV",
    package: "DSTV CONFAM",
    plan_amount: "4587",
  },
  {
    id: 23,
    cableplan_id: "23",
    cable: "DSTV",
    package: "DStv Asia",
    plan_amount: "6200",
  },
  {
    id: 7,
    cableplan_id: "7",
    cable: "DSTV",
    package: "DStv Compact",
    plan_amount: "7900",
  },
  {
    id: 29,
    cableplan_id: "29",
    cable: "DSTV",
    package: "DStv Compact + Extra View",
    plan_amount: "10400",
  },
  {
    id: 8,
    cableplan_id: "8",
    cable: "DSTV",
    package: "DStv Compact Plus",
    plan_amount: "12400",
  },
  {
    id: 32,
    cableplan_id: "32",
    cable: "DSTV",
    package: "DStv compact plus + extra view",
    plan_amount: "14826",
  },
  {
    id: 9,
    cableplan_id: "9",
    cable: "DSTV",
    package: "DStv Premium",
    plan_amount: "17940",
  },
  {
    id: 34,
    cableplan_id: "34",
    cable: "DSTV",
    package: "DStv premium extra view",
    plan_amount: "20796",
  },
];
const STARTIME = [
  {
    id: 42,
    cableplan_id: "42",
    cable: "STARTIME",
    package: "Nova - 90 Naira - 1 Day",
    plan_amount: "90",
  },
  {
    id: 43,
    cableplan_id: "43",
    cable: "STARTIME",
    package: "Basic - 160 Naira - 1 Day",
    plan_amount: "160",
  },
  {
    id: 44,
    cableplan_id: "44",
    cable: "STARTIME",
    package: "Smart - 200 Naira - 1 Day",
    plan_amount: "200",
  },
  {
    id: 37,
    cableplan_id: "37",
    cable: "STARTIME",
    package: "Nova - 300 Naira - 1 Week",
    plan_amount: "300",
  },
  {
    id: 45,
    cableplan_id: "45",
    cable: "STARTIME",
    package: "Classic - 320 Naira - 1 Day",
    plan_amount: "320",
  },
  {
    id: 46,
    cableplan_id: "46",
    cable: "STARTIME",
    package: "Super - 400 Naira - 1 Day",
    plan_amount: "400",
  },
  {
    id: 38,
    cableplan_id: "38",
    cable: "STARTIME",
    package: "Basic - 600 Naira - 1 Week",
    plan_amount: "600",
  },
  {
    id: 39,
    cableplan_id: "39",
    cable: "STARTIME",
    package: "Smart - 700 Naira - 1 Week",
    plan_amount: "700",
  },
  {
    id: 24,
    cableplan_id: "24",
    cable: "STARTIME",
    package: "NOVA-900-1 month",
    plan_amount: "900",
  },
  {
    id: 40,
    cableplan_id: "40",
    cable: "STARTIME",
    package: "Classic - 1200 Naira - 1 Week",
    plan_amount: "1200",
  },
  {
    id: 41,
    cableplan_id: "41",
    cable: "STARTIME",
    package: "Super - 1,500 Naira - 1 Week",
    plan_amount: "1500",
  },
  {
    id: 49,
    cableplan_id: "49",
    cable: "STARTIME",
    package: "Basic-1,700 Naira- 1 Month",
    plan_amount: "1700",
  },
  {
    id: 25,
    cableplan_id: "25",
    cable: "STARTIME",
    package: "BASIC-1700-1month",
    plan_amount: "1700",
  },
  {
    id: 26,
    cableplan_id: "26",
    cable: "STARTIME",
    package: "Smart-2200-1month",
    plan_amount: "2200",
  },
  {
    id: 51,
    cableplan_id: "51",
    cable: "STARTIME",
    package: "Smart - 2,200 Naira - 1Month",
    plan_amount: "2200",
  },
  {
    id: 27,
    cableplan_id: "27",
    cable: "STARTIME",
    package: "Classic-2500-1month",
    plan_amount: "2500",
  },
  {
    id: 50,
    cableplan_id: "50",
    cable: "STARTIME",
    package: "classic -2,500 Naira- 1Month",
    plan_amount: "2500",
  },
  {
    id: 28,
    cableplan_id: "28",
    cable: "STARTIME",
    package: "Super-4200-1month",
    plan_amount: "4200",
  },
  {
    id: 48,
    cableplan_id: "48",
    cable: "STARTIME",
    package: "Super-4,200 Naira- 1 Month",
    plan_amount: "4200",
  },
];
module.exports = { GOTV,DSTV, STARTIME };
