const MTN_SME = [
  {
    id: 157,
    dataplan_id: "157",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "1 day SOCIAL",
    plan: "20MB (Facebook)",
    plan_amount: "19",
    my_price: "39",
    resellerPrice: "29",
    apiPrice: "24",
    planCostPrice: 19.4,
  },
  {
    id: 158,
    dataplan_id: "158",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "1 day SOCIAL",
    plan: "20MB (Whatsapp)",
    plan_amount: "19",
    my_price: "39",
    resellerPrice: "29",
    apiPrice: "24",
    planCostPrice: 19.4,
  },
  {
    id: 159,
    dataplan_id: "159",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "1 day SOCIAL",
    plan: "150MB (Tiktok)",
    plan_amount: "48",
    my_price: "68",
    resellerPrice: "58",
    apiPrice: "54",
    planCostPrice: 48.5,
  },
  {
    id: 190,
    dataplan_id: "190",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "110MB",
    plan_amount: "97",
    my_price: "117",
    resellerPrice: "107",
    apiPrice: "102",
    planCostPrice: 97.0,
  },
  {
    id: 147,
    dataplan_id: "147",
    network: 1,
    plan_network: "MTN",
    plan_type: "Awoof",
    month_validate: "1 day Awoof",
    plan: "1GB Awoof (do not buy if you owe MTN)",
    plan_amount: "285",
    my_price: "305",
    resellerPrice: "295",
    apiPrice: "290",
    planCostPrice: 285.0,
  },
  {
    id: 136,
    dataplan_id: "136",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "500MB",
    plan_amount: "340",
    my_price: "360",
    resellerPrice: "350",
    apiPrice: "344",
    planCostPrice: 339.5,
  },
  {
    id: 150,
    dataplan_id: "150",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "1GB",
    plan_amount: "485",
    my_price: "505",
    resellerPrice: "495",
    apiPrice: "490",
    planCostPrice: 485.0,
  },
  {
    id: 155,
    dataplan_id: "155",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "1.5GB",
    plan_amount: "582",
    my_price: "602",
    resellerPrice: "592",
    apiPrice: "587",
    planCostPrice: 582.0,
  },
  {
    id: 438,
    dataplan_id: "438",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "2.5GB",
    plan_amount: "727",
    my_price: "747",
    resellerPrice: "737",
    apiPrice: "732",
    planCostPrice: 727.0,
  },
  {
    id: 146,
    dataplan_id: "146",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "2GB",
    plan_amount: "728",
    my_price: "748",
    resellerPrice: "738",
    apiPrice: "733",
    planCostPrice: 728.0,
  },
  {
    id: 133,
    dataplan_id: "133",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "3.5GB",
    plan_amount: "965",
    my_price: "985",
    resellerPrice: "975",
    apiPrice: "970",
    planCostPrice: 965.0,
  },
  {
    id: 153,
    dataplan_id: "153",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "3.2GB",
    plan_amount: "970",
    my_price: "990",
    resellerPrice: "980",
    apiPrice: "975",
    planCostPrice: 970.0,
  },
  {
    id: 439,
    dataplan_id: "439",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "1 day Gifting",
    plan: "3.5GB",
    plan_amount: "970",
    my_price: "990",
    resellerPrice: "980",
    apiPrice: "975",
    planCostPrice: 970.0,
  },
  {
    id: 134,
    dataplan_id: "134",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "4GB",
    plan_amount: "1158",
    my_price: "1178",
    resellerPrice: "1168",
    apiPrice: "1163",
    planCostPrice: 1158.0,
  },
  {
    id: 137,
    dataplan_id: "137",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "5.5GB",
    plan_amount: "1477",
    my_price: "1497",
    resellerPrice: "1487",
    apiPrice: "1482",
    planCostPrice: 1477.0,
  },
  {
    id: 138,
    dataplan_id: "138",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "7GB",
    plan_amount: "1737",
    my_price: "1757",
    resellerPrice: "1747",
    apiPrice: "1742",
    planCostPrice: 1737.0,
  },
  {
    id: 161,
    dataplan_id: "161",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "7 days SOCIAL",
    plan: "40MB (Facebook)",
    plan_amount: "48",
    my_price: "68",
    resellerPrice: "58",
    apiPrice: "54",
    planCostPrice: 48.5,
  },
  {
    id: 162,
    dataplan_id: "162",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "7 days SOCIAL",
    plan: "40MB (Whatsapp)",
    plan_amount: "48",
    my_price: "68",
    resellerPrice: "58",
    apiPrice: "54",
    planCostPrice: 48.5,
  },
  {
    id: 167,
    dataplan_id: "167",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "7 days SOCIAL",
    plan: "470MB (All Social)",
    plan_amount: "194",
    my_price: "214",
    resellerPrice: "204",
    apiPrice: "199",
    planCostPrice: 194.0,
  },
  {
    id: 101,
    dataplan_id: "101",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "500.0MB",
    plan_amount: "300",
    my_price: "320",
    resellerPrice: "310",
    apiPrice: "305",
    planCostPrice: 300.0,
  },
  {
    id: 163,
    dataplan_id: "163",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "7 days SOCIAL",
    plan: "2GB (Tiktok)",
    plan_amount: "388",
    my_price: "408",
    resellerPrice: "398",
    apiPrice: "393",
    planCostPrice: 388.0,
  },
  {
    id: 102,
    dataplan_id: "102",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "1GB",
    plan_amount: "395",
    my_price: "415",
    resellerPrice: "405",
    apiPrice: "400",
    planCostPrice: 395.0,
  },
  {
    id: 192,
    dataplan_id: "192",
    network: 1,
    plan_network: "MTN",
    plan_type: "DataShare",
    month_validate: "7 days DataShare",
    plan: "1GB",
    plan_amount: "420",
    my_price: "440",
    resellerPrice: "430",
    apiPrice: "425",
    planCostPrice: 420.0,
  },
  {
    id: 184,
    dataplan_id: "184",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "500MB",
    plan_amount: "485",
    my_price: "505",
    resellerPrice: "495",
    apiPrice: "490",
    planCostPrice: 485.0,
  },
  {
    id: 180,
    dataplan_id: "180",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "1GB",
    plan_amount: "776",
    my_price: "796",
    resellerPrice: "786",
    apiPrice: "781",
    planCostPrice: 776.0,
  },
  {
    id: 145,
    dataplan_id: "145",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "3.5GB",
    plan_amount: "1445",
    my_price: "1465",
    resellerPrice: "1455",
    apiPrice: "1450",
    planCostPrice: 1445.0,
  },
  {
    id: 154,
    dataplan_id: "154",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "6GB",
    plan_amount: "2425",
    my_price: "2445",
    resellerPrice: "2435",
    apiPrice: "2430",
    planCostPrice: 2425.0,
  },
  {
    id: 182,
    dataplan_id: "182",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "11GB",
    plan_amount: "3395",
    my_price: "3415",
    resellerPrice: "3405",
    apiPrice: "3400",
    planCostPrice: 3395.0,
  },
  {
    id: 172,
    dataplan_id: "172",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "15GB",
    plan_amount: "3880",
    my_price: "3900",
    resellerPrice: "3890",
    apiPrice: "3885",
    planCostPrice: 3880.0,
  },
  {
    id: 434,
    dataplan_id: "434",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "14 days Gifting",
    plan: "12.5GB",
    plan_amount: "4365",
    my_price: "4385",
    resellerPrice: "4375",
    apiPrice: "4370",
    planCostPrice: 4365.0,
  },
  {
    id: 198,
    dataplan_id: "198",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "20GB",
    plan_amount: "4850",
    my_price: "4870",
    resellerPrice: "4860",
    apiPrice: "4855",
    planCostPrice: 4850.0,
  },
  {
    id: 435,
    dataplan_id: "435",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "14 days Gifting",
    plan: "18GB",
    plan_amount: "5820",
    my_price: "5840",
    resellerPrice: "5830",
    apiPrice: "5825",
    planCostPrice: 5820.0,
  },
  {
    id: 436,
    dataplan_id: "436",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "14 days Gifting",
    plan: "28GB",
    plan_amount: "7760",
    my_price: "7780",
    resellerPrice: "7770",
    apiPrice: "7765",
    planCostPrice: 7760.0,
  },
  {
    id: 437,
    dataplan_id: "437",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "14 days Gifting",
    plan: "40GB",
    plan_amount: "9700",
    my_price: "9720",
    resellerPrice: "9710",
    apiPrice: "9705",
    planCostPrice: 9700.0,
  },
  {
    id: 164,
    dataplan_id: "164",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "30 days SOCIAL",
    plan: "120MB (Facebook)",
    plan_amount: "146",
    my_price: "166",
    resellerPrice: "156",
    apiPrice: "150",
    planCostPrice: 145.5,
  },
  {
    id: 165,
    dataplan_id: "165",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "30 days SOCIAL",
    plan: "120MB (Whatsapp)",
    plan_amount: "146",
    my_price: "166",
    resellerPrice: "156",
    apiPrice: "150",
    planCostPrice: 145.5,
  },
  {
    id: 166,
    dataplan_id: "166",
    network: 1,
    plan_network: "MTN",
    plan_type: "SOCIAL",
    month_validate: "30 days SOCIAL",
    plan: "1.2GB (All Social)",
    plan_amount: "436",
    my_price: "456",
    resellerPrice: "446",
    apiPrice: "442",
    planCostPrice: 436.5,
  },
  {
    id: 426,
    dataplan_id: "426",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "1GB Datashare monthly",
    plan_amount: "530",
    my_price: "550",
    resellerPrice: "540",
    apiPrice: "535",
    planCostPrice: 530.0,
  },
  {
    id: 103,
    dataplan_id: "103",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "2GB",
    plan_amount: "900",
    my_price: "920",
    resellerPrice: "910",
    apiPrice: "905",
    planCostPrice: 900.0,
  },
  {
    id: 104,
    dataplan_id: "104",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "3GB",
    plan_amount: "1250",
    my_price: "1270",
    resellerPrice: "1260",
    apiPrice: "1255",
    planCostPrice: 1250.0,
  },
  {
    id: 173,
    dataplan_id: "173",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "2GB",
    plan_amount: "1455",
    my_price: "1475",
    resellerPrice: "1465",
    apiPrice: "1460",
    planCostPrice: 1455.0,
  },
  {
    id: 105,
    dataplan_id: "105",
    network: 1,
    plan_network: "MTN",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "5GB",
    plan_amount: "1800",
    my_price: "1820",
    resellerPrice: "1810",
    apiPrice: "1805",
    planCostPrice: 1800.0,
  },
  {
    id: 174,
    dataplan_id: "174",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "2.7GB",
    plan_amount: "1940",
    my_price: "1960",
    resellerPrice: "1950",
    apiPrice: "1945",
    planCostPrice: 1940.0,
  },
  {
    id: 183,
    dataplan_id: "183",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "3.5GB",
    plan_amount: "2425",
    my_price: "2445",
    resellerPrice: "2435",
    apiPrice: "2430",
    planCostPrice: 2425.0,
  },
  {
    id: 185,
    dataplan_id: "185",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "7GB",
    plan_amount: "3395",
    my_price: "3415",
    resellerPrice: "3405",
    apiPrice: "3400",
    planCostPrice: 3395.0,
  },
  {
    id: 175,
    dataplan_id: "175",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "10GB",
    plan_amount: "4365",
    my_price: "4385",
    resellerPrice: "4375",
    apiPrice: "4370",
    planCostPrice: 4365.0,
  },
  {
    id: 171,
    dataplan_id: "171",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "12.5GB",
    plan_amount: "5335",
    my_price: "5355",
    resellerPrice: "5345",
    apiPrice: "5340",
    planCostPrice: 5335.0,
  },
  {
    id: 176,
    dataplan_id: "176",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "16.5GB",
    plan_amount: "6305",
    my_price: "6325",
    resellerPrice: "6315",
    apiPrice: "6310",
    planCostPrice: 6305.0,
  },
  {
    id: 186,
    dataplan_id: "186",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "20GB",
    plan_amount: "7275",
    my_price: "7295",
    resellerPrice: "7285",
    apiPrice: "7280",
    planCostPrice: 7275.0,
  },
  {
    id: 187,
    dataplan_id: "187",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "25GB",
    plan_amount: "8730",
    my_price: "8750",
    resellerPrice: "8740",
    apiPrice: "8735",
    planCostPrice: 8730.0,
  },
  {
    id: 177,
    dataplan_id: "177",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "36GB",
    plan_amount: "10670",
    my_price: "10690",
    resellerPrice: "10680",
    apiPrice: "10675",
    planCostPrice: 10670.0,
  },
  {
    id: 199,
    dataplan_id: "199",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "65GB",
    plan_amount: "15520",
    my_price: "15540",
    resellerPrice: "15530",
    apiPrice: "15525",
    planCostPrice: 15520.0,
  },
  {
    id: 178,
    dataplan_id: "178",
    network: 1,
    plan_network: "MTN",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "75GB",
    plan_amount: "17300",
    my_price: "17320",
    resellerPrice: "17310",
    apiPrice: "17305",
    planCostPrice: 17300.0,
  },
];
const GLO = 
[
  {
    id: 220,
    dataplan_id: "220",
    network: 2,
    plan_network: "GLO",
    plan_type: "Awoof",
    month_validate: "1 day Awoof",
    plan: "750MB",
    plan_amount: "188",
    my_price: "208",
    resellerPrice: "198",
    apiPrice: "193",
    planCostPrice: 188.0,
  },
  {
    id: 408,
    dataplan_id: "408",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "3 days SME",
    plan: "1GB",
    plan_amount: "240",
    my_price: "260",
    resellerPrice: "250",
    apiPrice: "245",
    planCostPrice: 240.0,
  },
  {
    id: 221,
    dataplan_id: "221",
    network: 2,
    plan_network: "GLO",
    plan_type: "Awoof",
    month_validate: "1 day Awoof",
    plan: "1.5GB",
    plan_amount: "282",
    my_price: "302",
    resellerPrice: "292",
    apiPrice: "287",
    planCostPrice: 282.0,
  },
  {
    id: 222,
    dataplan_id: "222",
    network: 2,
    plan_network: "GLO",
    plan_type: "Awoof",
    month_validate: "2 days Awoof",
    plan: "2.5GB",
    plan_amount: "470",
    my_price: "490",
    resellerPrice: "480",
    apiPrice: "475",
    planCostPrice: 470.0,
  },
  {
    id: 411,
    dataplan_id: "411",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "3 days SME",
    plan: "3GB",
    plan_amount: "720",
    my_price: "740",
    resellerPrice: "730",
    apiPrice: "725",
    planCostPrice: 720.0,
  },
  {
    id: 414,
    dataplan_id: "414",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "30 days SME",
    plan: "5GB",
    plan_amount: "1190",
    my_price: "1210",
    resellerPrice: "1200",
    apiPrice: "1195",
    planCostPrice: 1190.0,
  },
  {
    id: 409,
    dataplan_id: "409",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "14 days SME",
    plan: "500MB",
    plan_amount: "195",
    my_price: "215",
    resellerPrice: "205",
    apiPrice: "200",
    planCostPrice: 195.0,
  },
  {
    id: 410,
    dataplan_id: "410",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "1GB",
    plan_amount: "281",
    my_price: "301",
    resellerPrice: "291",
    apiPrice: "286",
    planCostPrice: 281.0,
  },
  {
    id: 407,
    dataplan_id: "407",
    network: 2,
    plan_network: "GLO",
    plan_type: "Awoof",
    month_validate: "14 days Awoof",
    plan: "1GB (Night)",
    plan_amount: "290",
    my_price: "310",
    resellerPrice: "300",
    apiPrice: "295",
    planCostPrice: 290.0,
  },
  {
    id: 428,
    dataplan_id: "428",
    network: 2,
    plan_network: "GLO",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "1.5GB (WhatsApp, Instagram, Tiktok)",
    plan_amount: "470",
    my_price: "490",
    resellerPrice: "480",
    apiPrice: "475",
    planCostPrice: 470.0,
  },
  {
    id: 412,
    dataplan_id: "412",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "3GB",
    plan_amount: "835",
    my_price: "855",
    resellerPrice: "845",
    apiPrice: "840",
    planCostPrice: 835.0,
  },
  {
    id: 413,
    dataplan_id: "413",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "14 days CG",
    plan: "3GB (Night)",
    plan_amount: "840",
    my_price: "860",
    resellerPrice: "850",
    apiPrice: "845",
    planCostPrice: 840.0,
  },
  {
    id: 415,
    dataplan_id: "415",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "5GB",
    plan_amount: "1380",
    my_price: "1400",
    resellerPrice: "1390",
    apiPrice: "1385",
    planCostPrice: 1380.0,
  },
  {
    id: 223,
    dataplan_id: "223",
    network: 2,
    plan_network: "GLO",
    plan_type: "SME",
    month_validate: "7 days SME",
    plan: "10GB",
    plan_amount: "1880",
    my_price: "1900",
    resellerPrice: "1890",
    apiPrice: "1885",
    planCostPrice: 1880.0,
  },
  {
    id: 201,
    dataplan_id: "201",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "500MB",
    plan_amount: "219",
    my_price: "239",
    resellerPrice: "229",
    apiPrice: "224",
    planCostPrice: 219.0,
  },
  {
    id: 202,
    dataplan_id: "202",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "1GB",
    plan_amount: "400",
    my_price: "420",
    resellerPrice: "410",
    apiPrice: "405",
    planCostPrice: 400.0,
  },
  {
    id: 203,
    dataplan_id: "203",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "2GB",
    plan_amount: "800",
    my_price: "820",
    resellerPrice: "810",
    apiPrice: "805",
    planCostPrice: 800.0,
  },
  {
    id: 204,
    dataplan_id: "204",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "3GB",
    plan_amount: "1200",
    my_price: "1220",
    resellerPrice: "1210",
    apiPrice: "1205",
    planCostPrice: 1200.0,
  },
  {
    id: 205,
    dataplan_id: "205",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "5GB",
    plan_amount: "2000",
    my_price: "2020",
    resellerPrice: "2010",
    apiPrice: "2005",
    planCostPrice: 2000.0,
  },
  {
    id: 206,
    dataplan_id: "206",
    network: 2,
    plan_network: "GLO",
    plan_type: "CG",
    month_validate: "30 days CG",
    plan: "10GB",
    plan_amount: "4000",
    my_price: "4020",
    resellerPrice: "4010",
    apiPrice: "4005",
    planCostPrice: 4000.0,
  },
  {
    id: 429,
    dataplan_id: "429",
    network: 2,
    plan_network: "GLO",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "Unlimited (Glo Router)",
    plan_amount: "18800",
    my_price: "18820",
    resellerPrice: "18810",
    apiPrice: "18805",
    planCostPrice: 18800.0,
  },
  {
    id: 430,
    dataplan_id: "430",
    network: 2,
    plan_network: "GLO",
    plan_type: "Gifting",
    month_validate: "365 days Gifting",
    plan: "1000GB",
    plan_amount: "141000",
    my_price: "141020",
    resellerPrice: "141010",
    apiPrice: "141005",
    planCostPrice: 141000.0,
  },
];
const AIRTEL = 
[
  {
    id: 320,
    dataplan_id: "320",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "1 day Awoof",
    plan: "150MB",
    plan_amount: "70",
    my_price: "90",
    resellerPrice: "80",
    apiPrice: "75",
    planCostPrice: 70.0,
  },
  {
    id: 321,
    dataplan_id: "321",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "2 days Awoof",
    plan: "300MB",
    plan_amount: "128",
    my_price: "148",
    resellerPrice: "138",
    apiPrice: "133",
    planCostPrice: 128.0,
  },
  {
    id: 322,
    dataplan_id: "322",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "2 days Awoof",
    plan: "600MB",
    plan_amount: "260",
    my_price: "280",
    resellerPrice: "270",
    apiPrice: "265",
    planCostPrice: 260.0,
  },
  {
    id: 323,
    dataplan_id: "323",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "5 days Awoof",
    plan: "1GB (Social)",
    plan_amount: "360",
    my_price: "380",
    resellerPrice: "370",
    apiPrice: "365",
    planCostPrice: 360.0,
  },
  {
    id: 418,
    dataplan_id: "418",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "1 day Awoof",
    plan: "1.5GB",
    plan_amount: "480",
    my_price: "500",
    resellerPrice: "490",
    apiPrice: "485",
    planCostPrice: 480.0,
  },
  {
    id: 425,
    dataplan_id: "425",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "2GB",
    plan_amount: "580",
    my_price: "600",
    resellerPrice: "590",
    apiPrice: "585",
    planCostPrice: 580.0,
  },
  {
    id: 422,
    dataplan_id: "422",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "2 days Gifting",
    plan: "3GB",
    plan_amount: "723",
    my_price: "743",
    resellerPrice: "733",
    apiPrice: "728",
    planCostPrice: 723.0,
  },
  {
    id: 423,
    dataplan_id: "423",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "1GB",
    plan_amount: "770",
    my_price: "790",
    resellerPrice: "780",
    apiPrice: "775",
    planCostPrice: 770.0,
  },
  {
    id: 338,
    dataplan_id: "338",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "500MB",
    plan_amount: "490",
    my_price: "510",
    resellerPrice: "500",
    apiPrice: "495",
    planCostPrice: 490.0,
  },
  {
    id: 339,
    dataplan_id: "339",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "7 days Gifting",
    plan: "1GB",
    plan_amount: "785",
    my_price: "805",
    resellerPrice: "795",
    apiPrice: "790",
    planCostPrice: 785.0,
  },
  {
    id: 330,
    dataplan_id: "330",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "14 days Awoof",
    plan: "5GB",
    plan_amount: "1470",
    my_price: "1490",
    resellerPrice: "1480",
    apiPrice: "1475",
    planCostPrice: 1470.0,
  },
  {
    id: 419,
    dataplan_id: "419",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "7 days Awoof",
    plan: "6GB",
    plan_amount: "2400",
    my_price: "2420",
    resellerPrice: "2410",
    apiPrice: "2405",
    planCostPrice: 2400.0,
  },
  {
    id: 342,
    dataplan_id: "342",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "2GB",
    plan_amount: "1470",
    my_price: "1490",
    resellerPrice: "1480",
    apiPrice: "1475",
    planCostPrice: 1470.0,
  },
  {
    id: 343,
    dataplan_id: "343",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "3GB",
    plan_amount: "1955",
    my_price: "1975",
    resellerPrice: "1965",
    apiPrice: "1960",
    planCostPrice: 1955.0,
  },
  {
    id: 344,
    dataplan_id: "344",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "4GB",
    plan_amount: "2445",
    my_price: "2465",
    resellerPrice: "2455",
    apiPrice: "2450",
    planCostPrice: 2445.0,
  },
  {
    id: 345,
    dataplan_id: "345",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "8GB",
    plan_amount: "2935",
    my_price: "2955",
    resellerPrice: "2945",
    apiPrice: "2940",
    planCostPrice: 2935.0,
  },
  {
    id: 327,
    dataplan_id: "327",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Awoof",
    month_validate: "30 days Awoof",
    plan: "10GB",
    plan_amount: "3060",
    my_price: "3080",
    resellerPrice: "3070",
    apiPrice: "3065",
    planCostPrice: 3060.0,
  },
  {
    id: 421,
    dataplan_id: "421",
    network: 3,
    plan_network: "AIRTEL",
    plan_type: "Gifting",
    month_validate: "30 days Gifting",
    plan: "13GB",
    plan_amount: "4885",
    my_price: "4905",
    resellerPrice: "4895",
    apiPrice: "4890",
    planCostPrice: 4885.0,
  },
];
const NMOBILE = [
  {
    id: 401,
    dataplan_id: "401",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "1GB",
    plan_amount: "350",
    my_price: "350",
    resellerPrice: "340",
    apiPrice: "340",
  },
  {
    id: 402,
    dataplan_id: "402",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "1.5GB",
    plan_amount: "525",
    my_price: "525",
    resellerPrice: "510",
    apiPrice: "510",
  },
  {
    id: 403,
    dataplan_id: "403",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "2GB",
    plan_amount: "700",
    my_price: "700",
    resellerPrice: "680",
    apiPrice: "680",
  },
  {
    id: 404,
    dataplan_id: "404",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "3GB",
    plan_amount: "1050",
    my_price: "1020",
    resellerPrice: "1020",
    apiPrice: "1020",
  },
  {
    id: 405,
    dataplan_id: "405",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "5GB",
    plan_amount: "1750",
    my_price: "1750",
    resellerPrice: "1700",
    apiPrice: "1700",
  },
  {
    id: 406,
    dataplan_id: "406",
    network: 6,
    plan_type: "SME",
    plan_network: "9MOBILE",
    month_validate: "30 days",
    plan: "10GB",
    plan_amount: "3500",
    my_price: "3500",
    resellerPrice: "3400",
    apiPrice: "3400",
  },
];

module.exports = { MTN_SME, GLO, AIRTEL, NMOBILE };
